apiVersion: v1
kind: Service
metadata:
  name: panda-service
spec:
  type: NodePort
  selector:
    app: panda
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007 # Custom NodePort; can be between 30000-32767

